### ISSUE TITLE
Older months appear randomly empty

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#121] opened 2023-05-29 09:46 UTC
Some older months appear to be randomly not showing daily worklogs. For Tim's personal account it's March 2023 and November 2022, one of my colleague has the issues with April 2023. So it's unclear why.

Could you please investigate?

**Comment by bedrich-schindler** [comment] 2023-06-04 13:01
@cetcondor Can you specify what exactly do you mean by "not showing daily worklogs". I ran instance of production in the container to be able to change credentials and login as you to check it and I see that work logs are shown for every month. If you think that some worklogs are missing, I can check it again database row by row. But first, I would like to have detailed explanation what is wrong.

The only thing I observed is that for those months, worked time is missing. That can be caused by change in calculation. If current calculation differs from what is stored in database for closed month, those times are hidden to prevent confusion as the calculation formula cannot be versioned. This feature has been introduced some time ago when there were major changes in calculation formula.

**Comment by bedrich-schindler** [comment] 2023-06-04 13:02
If you want to post more details containing personal data, you can contact me directly via email bedrich.schindler@gmail.com

**Comment by bedrich-schindler** [comment] 2023-06-12 07:09
The difference is caused by https://github.com/DBJRdev/ditt-client/issues/99 (https://github.com/DBJRdev/ditt-client/commit/a271bfe613267f1fd6e7fc31a847ab2d6721a0a3). Home Office, Business trip, Training and are calculated as 0 instead of whole day. This causes differences.

I will talk to @davidurban as there is request change in #99, we need to figure out the problem

**Comment by bedrich-schindler** [comment] 2023-06-15 13:21
Changes for Business trip rolled back in #99, so the calculation should be fixed for those months where there are Business trips.

**Closed as completed by bedrich-schindler** 2023-06-15 13:21 UTC
Labels: bug, approved, PRIORITY, AdB
